In [1]:
import pandas as pd

In [106]:
data = pd.read_csv('../Data/tableau_table.csv')
data.Q.value_counts()

1    82
3    71
2    50
4    45
Name: Q, dtype: int64

In [119]:
Q = ['Q1','Q2','Q3','Q4']


q = 'Q1'
a = data[f'{q}_probabilities'].str.split(',')[0][1].strip(']')
a = float(a)

a

0.009937558432496052

In [117]:
    
X = data[['Q1_Prob','Q2_Prob','Q3_Prob','Q4_Prob']]
y = data.Q
X

      Q1_Prob   Q2_Prob   Q3_Prob  Q4_Prob
0    0.009938  0.012798  0.006015  0.96952
1    0.009938  0.012798  0.006015  0.96952
2    0.009938  0.012798  0.006015  0.96952
3    0.009938  0.012798  0.006015  0.96952
4    0.009938  0.012798  0.006015  0.96952
..        ...       ...       ...      ...
243  0.009938  0.012798  0.006015  0.96952
244  0.009938  0.012798  0.006015  0.96952
245  0.009938  0.012798  0.006015  0.96952
246  0.009938  0.012798  0.006015  0.96952
247  0.009938  0.012798  0.006015  0.96952

[248 rows x 4 columns]

In [109]:
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV



x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = .2, random_state = 42)

In [110]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=32, random_state=42)
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)

In [111]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.36

In [112]:
X

      Q1_Prob   Q2_Prob   Q3_Prob  Q4_Prob
0    0.009938  0.012798  0.006015  0.96952
1    0.009938  0.012798  0.006015  0.96952
2    0.009938  0.012798  0.006015  0.96952
3    0.009938  0.012798  0.006015  0.96952
4    0.009938  0.012798  0.006015  0.96952
..        ...       ...       ...      ...
243  0.009938  0.012798  0.006015  0.96952
244  0.009938  0.012798  0.006015  0.96952
245  0.009938  0.012798  0.006015  0.96952
246  0.009938  0.012798  0.006015  0.96952
247  0.009938  0.012798  0.006015  0.96952

[248 rows x 4 columns]

In [113]:
data[['Q1_probabilities','Q2_probabilities','Q3_probabilities','Q4_probabilities']]

,Q1_probabilities,Q2_probabilities,Q3_probabilities,Q4_probabilities
0,"[0.9900624415675039, 0.009937558432496052]","[0.9872024692275917, 0.012797530772408269]","[0.9939853440372725, 0.0060146559627275616]","[0.030479877886147033, 0.969520122113853]"
1,"[0.11995925730469581, 0.8800407426953042]","[0.9563342878151998, 0.043665712184800205]","[0.9847584551660893, 0.01524154483391073]","[0.9786976543301501, 0.02130234566984989]"
2,"[0.9888317482652479, 0.01116825173475211]","[0.9839762819161306, 0.01602371808386938]","[0.1198178401852108, 0.8801821598147892]","[0.9919646521560592, 0.00803534784394078]"
3,"[0.9927110640618497, 0.00728893593815029]","[0.283728870384262, 0.716271129615738]","[0.983835610976363, 0.016164389023637076]","[0.991701251517981, 0.00829874848201899]"
4,"[0.959413938059762, 0.04058606194023799]","[0.9849644852004064, 0.015035514799593617]","[0.10772038055991329, 0.8922796194400867]","[0.9751230277308611, 0.024876972269138847]"
...,...,...,...,...
243,"[0.9900624415675039, 0.009937558432496052]","[0.9872024692275917, 0.012797530772408269]","[0.9939853440372725, 0.0060146559627275616]","[0.030479877886147033, 0.969520122113853]"
244,"[0.9881425746373823, 0.01185742536261766]","[0.9863672102017922, 0.013632789798207775]","[0.9904920928397499, 0.00950790716025006]","[0.989367174888377, 0.010632825111622946]"
245,"[0.11995925730469581, 0.8800407426953042]","[0.9563342878151998, 0.043665712184800205]","[0.9847584551660893, 0.01524154483391073]","[0.9786976543301501, 0.02130234566984989]"
246,"[0.9920316038061282, 0.00796839619387179]","[0.9830947581472335, 0.01690524185276649]","[0.04120769108837785, 0.9587923089116221]","[0.9913364166892068, 0.008663583310793206]"
247,"[0.04330838670256809, 0.9566916132974319]","[0.98667960319253, 0.013320396807469992]","[0.9855853463729229, 0.014414653627077056]","[0.9879201432860167, 0.012079856713983312]"