In [199]:
import pandas as pd

In [200]:
data = pd.read_csv('../Data/tableau_table.csv')
data.Q.value_counts()

1    82
3    71
2    50
4    45
Name: Q, dtype: int64

In [201]:
data.head(3)

,company,job_title,state,city,rating,target,salary,dateposted,summary,url,...,Q3_pred y,Q3_probabilities,Q4_y_test,Q4_pred y,Q4_probabilities,Q,Q1,Q2,Q3,Q4
0,comcentric,data scientist,+21 locationsremote,+21 locationsremote,4.2,4.0,208000.0,2022-04-17,"mentor and grow other software engineers, data...",https://www.indeed.com/rc/clk?jk=4c2d6184ae3a9...,...,0,"[0.9939853440372725, 0.0060146559627275616]",1,1,"[0.030479877886147033, 0.969520122113853]",4,0.0,0.0,0.0,1.0
1,calculated hire,data scientist,remote,remote,3.9,1.0,69000.0,2022-04-13,"remains alert to new techniques for insights, ...",https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...,...,0,"[0.9847584551660893, 0.01524154483391073]",0,0,"[0.9786976543301501, 0.02130234566984989]",1,1.0,0.0,0.0,0.0
2,revel,senior data scientist - routing algorithm,ny,remote in brooklyn,2.6,3.0,134000.0,2022-04-17,"lead the development of our ride assignment, r...",https://www.indeed.com/company/Revel/jobs/Seni...,...,1,"[0.1198178401852108, 0.8801821598147892]",0,0,"[0.9919646521560592, 0.00803534784394078]",3,0.0,0.0,1.0,0.0

In [202]:

def probs(row,i):
    x = row[i]
    return float(x.split(',')[1].strip(']'))

prob_list = ['Q1_probabilities','Q2_probabilities','Q3_probabilities','Q4_probabilities']


for i,j in zip(prob_list,['Q1_Probs','Q2_Probs','Q3_Probs','Q4_Probs']):
    data[j] = data.apply( lambda row : probs(row, i), axis = 1)
    data

In [203]:
data[prob_list+['Q1_Probs','Q2_Probs','Q3_Probs','Q4_Probs','Q']]

,Q1_probabilities,Q2_probabilities,Q3_probabilities,Q4_probabilities,Q1_Probs,Q2_Probs,Q3_Probs,Q4_Probs,Q
0,"[0.9900624415675039, 0.009937558432496052]","[0.9872024692275917, 0.012797530772408269]","[0.9939853440372725, 0.0060146559627275616]","[0.030479877886147033, 0.969520122113853]",0.009938,0.012798,0.006015,0.969520,4
1,"[0.11995925730469581, 0.8800407426953042]","[0.9563342878151998, 0.043665712184800205]","[0.9847584551660893, 0.01524154483391073]","[0.9786976543301501, 0.02130234566984989]",0.880041,0.043666,0.015242,0.021302,1
2,"[0.9888317482652479, 0.01116825173475211]","[0.9839762819161306, 0.01602371808386938]","[0.1198178401852108, 0.8801821598147892]","[0.9919646521560592, 0.00803534784394078]",0.011168,0.016024,0.880182,0.008035,3
3,"[0.9927110640618497, 0.00728893593815029]","[0.283728870384262, 0.716271129615738]","[0.983835610976363, 0.016164389023637076]","[0.991701251517981, 0.00829874848201899]",0.007289,0.716271,0.016164,0.008299,2
4,"[0.959413938059762, 0.04058606194023799]","[0.9849644852004064, 0.015035514799593617]","[0.10772038055991329, 0.8922796194400867]","[0.9751230277308611, 0.024876972269138847]",0.040586,0.015036,0.892280,0.024877,3
...,...,...,...,...,...,...,...,...,...
243,"[0.9900624415675039, 0.009937558432496052]","[0.9872024692275917, 0.012797530772408269]","[0.9939853440372725, 0.0060146559627275616]","[0.030479877886147033, 0.969520122113853]",0.009938,0.012798,0.006015,0.969520,4
244,"[0.9881425746373823, 0.01185742536261766]","[0.9863672102017922, 0.013632789798207775]","[0.9904920928397499, 0.00950790716025006]","[0.989367174888377, 0.010632825111622946]",0.011857,0.013633,0.009508,0.010633,2
245,"[0.11995925730469581, 0.8800407426953042]","[0.9563342878151998, 0.043665712184800205]","[0.9847584551660893, 0.01524154483391073]","[0.9786976543301501, 0.02130234566984989]",0.880041,0.043666,0.015242,0.021302,1
246,"[0.9920316038061282, 0.00796839619387179]","[0.9830947581472335, 0.01690524185276649]","[0.04120769108837785, 0.9587923089116221]","[0.9913364166892068, 0.008663583310793206]",0.007968,0.016905,0.958792,0.008664,3
247,"[0.04330838670256809, 0.9566916132974319]","[0.98667960319253, 0.013320396807469992]","[0.9855853463729229, 0.014414653627077056]","[0.9879201432860167, 0.012079856713983312]",0.956692,0.013320,0.014415,0.012080,1

In [204]:
    
X = data[['Q1_Probs','Q2_Probs','Q3_Probs','Q4_Probs']]
y = data.Q
X

     Q1_Probs  Q2_Probs  Q3_Probs  Q4_Probs
0    0.009938  0.012798  0.006015  0.969520
1    0.880041  0.043666  0.015242  0.021302
2    0.011168  0.016024  0.880182  0.008035
3    0.007289  0.716271  0.016164  0.008299
4    0.040586  0.015036  0.892280  0.024877
..        ...       ...       ...       ...
243  0.009938  0.012798  0.006015  0.969520
244  0.011857  0.013633  0.009508  0.010633
245  0.880041  0.043666  0.015242  0.021302
246  0.007968  0.016905  0.958792  0.008664
247  0.956692  0.013320  0.014415  0.012080

[248 rows x 4 columns]

In [205]:
from sklearn.model_selection import train_test_split, cross_validate, GridSearchCV



x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = .2, random_state = 42)

In [206]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=8, random_state=42)
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)

In [207]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.96

In [208]:
x_test['y_hat'] = y_pred

In [209]:
x_test['true_y'] = y_test.to_list()
x_test[x_test.y_hat != x_test.true_y]

     Q1_Probs  Q2_Probs  Q3_Probs  Q4_Probs  y_hat  true_y
117  0.052707  0.055492  0.026163  0.049241      1       2
55   0.075617  0.053915  0.086136  0.032533      1       3

In [210]:
z = len(x_test[x_test.y_hat != x_test.true_y])
zz = len(x_test)

In [211]:
print(zz/z)

25.0

In [212]:
print(zz,z)

50 2